BF: Skip camera devices with no available formats.
I have some virtual cameras on my system that have no available formats,
and this leads to e.g.:

>>> x = CameraDevice.getAvailableDevices()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "...\psychopy\hardware\camera\__init__.py", line 614, in getAvailableDevices
    minFrameRate = max(28, min([cam.frameRate for cam in allCams]))
ValueError: min() arg is an empty sequence

As far as I can tell, this is the only place where non-emptiness is assumed?