Use Image.frombytes() instead of removed .fromstring()
This prevents the following error

	  Traceback (most recent call last):
	  ...
	  ...
	    last_screen = win.getMovieFrame()
	  File "C:\Users\eoin.travers\Programs\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\site-packages\psychopy\visual\window.py", line 798, in getMovieFrame
	    im = self._getFrame(buffer=buffer)
	  File "C:\Users\eoin.travers\Programs\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\site-packages\psychopy\visual\window.py", line 820, in _getFrame
	    im = Image.fromstring(mode='RGBA', size=self.size, data=bufferDat)
	  File "C:\Users\eoin.travers\Programs\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\site-packages\PIL\Image.py", line 2053, in fromstring
	    "Please call frombytes() instead.")
	Exception: fromstring() has been removed. Please call frombytes() instead.