BF: exceptions in sound imported inconsistently
Getting a strange error in testing, as below. It's strange because the
error indicates that `psychopy.sound.exceptions` has no attribute
`DependencyError` BUT the import at the top of `sound/__init__.py`
was importing psychopy.exceptions NOT psychopy.sound.exceptions. It isn't clear why sound.exceptions
is being used instead.

Nonetheless I've revised the importing of the exceptions through the sound
lib so that:
- sound.exceptions does import those from psychopy.exceptions
- all sound backends fetch from sound.exceptions
- they import individual names rather than the exceptions module
  (in case that was being monkey-patched somehow)


```
...
psychopy/experiment/components/microphone/__init__.py:18: in <module>
    from psychopy.sound.microphone import Microphone, _hasPTB
psychopy/sound/__init__.py:98: in <module>
    except exceptions.DependencyError as e:
E   AttributeError: module 'psychopy.sound.exceptions' has no attribute 'DependencyError'
```