BF: Remove json from setup.cfg
`json` is a built-in Python library, so it causes this error on attempting installation:
    ERROR: Could not find a version that satisfies the requirement json (from PsychoPy==2020.1.3) (from versions: none)
    ERROR: No matching distribution found for json (from PsychoPy==2020.1.3)