BF: allow saving non-numeric data to excel format for TrialHandlerExt
Trying to save non-numeric data (e.g., strings) to excel files via the saveAsExcel method of the TrialHandlerExt class was throwing the following error: "AttributeError: 'numpy.ndarray' object has no attribute 'mask'"

Reason: non-numeric data do not use masked arrays in Psychopy, but rather object arrays.

Solution: for non-numeric data, create a code block respecting the convention for these data type, e.g., use '--' for missing values instead of masks.