BF: add extra git config settings to handle large projects and merging
Newer git installations will error if no merge policy is set (we want no rebase)

Also, if users commit a huge first push they will get an error
```
error: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500

send-pack: unexpected disconnect while reading sideband packet

fatal: the remote end hung up unexpectedly
```

We can fix these with more extended git config settings