FF: reverting activatePlugins frmo iohub init
Reverting ce4c68038a5aae7264029e87f3e75ab43f4475ed

This was causing the app not to start on MacOS
with err:
`AttributeError: module 'psychopy' has no attribute 'experiment'` maybe caused by some recursive import

This fix wasn't needed after all anyway - it could be handled faster by
adding the plugins paths to sys.path